#include "project.hpp"

#include <filesystem>
#include <fstream>

namespace arecomp {

namespace {

namespace fs = std::filesystem;

bool write_if_absent(const fs::path& path, const std::string& content) {
    if (fs::exists(path)) return false;   // never clobber hand-written port code
    std::ofstream out(path);
    out << content;
    return true;
}

std::string escape_backslashes(const std::string& text) {
    std::string out;
    for (char c : text) {
        if (c == '\\') out += '/';
        else out += c;
    }
    return out;
}

std::string region_kind_enum(const std::string& kind) {
    if (kind == "chip") return "RegionKind::Chip";
    if (kind == "fast") return "RegionKind::Fast";
    if (kind == "slow") return "RegionKind::Slow";
    if (kind == "rom") return "RegionKind::Rom";
    if (kind == "expansion") return "RegionKind::Expansion";
    return "RegionKind::Chip";
}

std::string permission_enum(const std::string& perms) {
    std::string out;
    if (perms.find('r') != std::string::npos) out += "PERM_R";
    if (perms.find('w') != std::string::npos) out += (out.empty() ? "" : " | ") + std::string("PERM_W");
    if (perms.find('x') != std::string::npos) out += (out.empty() ? "" : " | ") + std::string("PERM_X");
    return out.empty() ? "PERM_R" : out;
}

std::string hex(u32 value) {
    char buf[24];
    std::snprintf(buf, sizeof buf, "0x%08xu", value);
    return buf;
}

} // namespace

bool write_project(const Manifest& manifest, const AnalysisResult& analysis,
                   const ProjectOptions& options, std::string& error) {
    const fs::path root(options.output_dir);
    std::error_code ec;
    fs::create_directories(root / "generated", ec);
    fs::create_directories(root / "patch", ec);
    if (ec) {
        error = "cannot create " + options.output_dir + ": " + ec.message();
        return false;
    }

    const std::string framework = escape_backslashes(options.framework_root);

    // --- CMakeLists.txt (always regenerated: it lists generated sources) ---
    {
        std::ofstream out(root / "CMakeLists.txt");
        if (!out) {
            error = "cannot write CMakeLists.txt";
            return false;
        }
        out << "# Generated by arecomp for \"" << manifest.name << "\".\n"
            << "#\n"
            << "# This project contains translated game code. It is not part of the\n"
            << "# amiga-recomp repository and must not be committed to it.\n\n"
            << "cmake_minimum_required(VERSION 3.20)\n"
            << "project(" << manifest.id << " LANGUAGES CXX)\n\n"
            << "set(CMAKE_CXX_STANDARD 20)\n"
            << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n"
            << "if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)\n"
            << "  set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING \"\" FORCE)\n"
            << "endif()\n\n"
            << "set(AMIGA_RECOMP_ROOT \"" << framework << "\"\n"
            << "    CACHE PATH \"Path to the amiga-recomp framework\")\n\n"
            << "add_subdirectory(${AMIGA_RECOMP_ROOT}/runtime"
            << " ${CMAKE_BINARY_DIR}/amiga_runtime)\n\n"
            << "file(GLOB ARECOMP_GENERATED CONFIGURE_DEPENDS generated/*.cpp)\n"
            << "file(GLOB ARECOMP_PATCH CONFIGURE_DEPENDS patch/*.cpp)\n\n"
            << "add_executable(" << manifest.id << "\n"
            << "  main.cpp\n"
            << "  port.cpp\n"
            << "  ${ARECOMP_GENERATED}\n"
            << "  ${ARECOMP_PATCH}\n"
            << ")\n\n"
            << "target_include_directories(" << manifest.id
            << " PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/generated)\n"
            << "target_link_libraries(" << manifest.id
            << " PRIVATE amiga_runtime arecomp_warnings)\n";
    }

    // --- port.hpp (always regenerated: it reflects the manifest) ----------
    {
        std::ofstream out(root / "port.hpp");
        out << "// Generated by arecomp. Describes the machine this port runs on.\n"
            << "#pragma once\n\n"
            << "#include \"amiga_recomp/runtime.hpp\"\n\n"
            << "namespace port {\n\n"
            << "using namespace arecomp;\n\n"
            << "// Builds the guest address space described by the manifest.\n"
            << "void configure_memory(GuestMemory& memory);\n\n"
            << "// Loads the user-supplied game image. Returns false if it is\n"
            << "// missing: no game data ships with the port.\n"
            << "bool load_image(GuestMemory& memory, const std::string& path);\n\n"
            << "// Sets the captured entry state from the manifest.\n"
            << "void configure_cpu(M68kState& cpu);\n\n"
            << "// Registers native hooks. Hand-written; see patch/.\n"
            << "void install_hooks(Runtime& runtime);\n\n"
            << "// Maps the debug halt sentinel, if the manifest asked for one.\n"
            << "// Does nothing otherwise, so a real port carries no test scaffolding.\n"
            << "void configure_harness(GuestMemory& memory, M68kState& cpu);\n\n"
            << "constexpr const char* kName = \"" << manifest.name << "\";\n"
            << "constexpr const char* kDefaultImage = \""
            << escape_backslashes(manifest.input_path) << "\";\n"
            << "\n} // namespace port\n";
    }

    // --- port.cpp (always regenerated except the hook body) ---------------
    {
        std::ofstream out(root / "port.cpp");
        out << "// Generated by arecomp from the manifest. Do not edit; hand-written\n"
            << "// port code belongs in patch/.\n\n"
            << "#include \"port.hpp\"\n\n"
            << "#include <cstdio>\n"
            << "#include <vector>\n\n"
            << "#include \"amiga_recomp/halt_device.hpp\"\n"
            << "#include \"patch/hooks.hpp\"\n\n"
            << "namespace port {\n\n"
            << "void configure_memory(GuestMemory& memory) {\n";
        for (const MemoryRegionSpec& r : manifest.regions) {
            out << "    memory.add_ram(" << hex(r.start) << ", " << hex(r.size) << ", "
                << region_kind_enum(r.kind) << ", " << permission_enum(r.permissions)
                << ", \"" << r.kind << "\");\n";
        }
        out << "    memory.set_strict_unmapped("
            << (manifest.options.strict_address_errors ? "true" : "false") << ");\n"
            << "}\n\n"
            << "bool load_image(GuestMemory& memory, const std::string& path) {\n"
            << "    std::FILE* file = std::fopen(path.c_str(), \"rb\");\n"
            << "    if (!file) return false;\n"
            << "    std::vector<uint8_t> data;\n"
            << "    uint8_t buffer[65536];\n"
            << "    std::size_t n;\n"
            << "    while ((n = std::fread(buffer, 1, sizeof buffer, file)) > 0)\n"
            << "        data.insert(data.end(), buffer, buffer + n);\n"
            << "    std::fclose(file);\n"
            << "    return memory.load(" << hex(manifest.load_address)
            << ", data.data(), data.size());\n"
            << "}\n\n"
            << "void configure_cpu(M68kState& cpu) {\n"
            << "    cpu.pc = " << hex(manifest.cpu.entry) << ";\n"
            << "    cpu.set_sr(0x" << std::hex << manifest.cpu.initial_sr << std::dec << "u);\n";
        if (manifest.cpu.has_registers) {
            for (int i = 0; i < 8; ++i)
                out << "    cpu.d[" << i << "] = " << hex(manifest.cpu.d[i]) << ";\n";
            for (int i = 0; i < 8; ++i)
                out << "    cpu.a[" << i << "] = " << hex(manifest.cpu.a[i]) << ";\n";
        }
        out << "}\n\n"
            << "void install_hooks(Runtime& runtime) {\n"
            << "    patch::install(runtime);\n"
            << "}\n\n"
            << "void configure_harness(GuestMemory& memory, M68kState& cpu) {\n";
        if (manifest.harness_halt_address != 0) {
            out << "    static HaltDevice device(cpu);\n"
                << "    memory.map_device(" << hex(manifest.harness_halt_address)
                << ", GuestMemory::kPageSize, &device, RegionKind::Expansion,\n"
                << "                      \"halt-sentinel\");\n";
        } else {
            out << "    (void)memory;\n    (void)cpu;\n";
        }
        out << "}\n\n"
            << "} // namespace port\n";
    }

    // --- patch/hooks.hpp and patch/hooks.cpp (written once) ---------------
    {
        std::string header =
            "// Hand-written native code for this port: hooks, function\n"
            "// replacements and enhancements (AMIGA_RECOMP.md 35, 36).\n"
            "//\n"
            "// arecomp will not overwrite this file once it exists.\n"
            "#pragma once\n\n"
            "#include \"amiga_recomp/runtime.hpp\"\n\n"
            "namespace patch {\n\n"
            "// Called once at start-up, after the block table is installed.\n"
            "void install(arecomp::Runtime& runtime);\n\n"
            "} // namespace patch\n";
        write_if_absent(root / "patch" / "hooks.hpp", header);

        std::string source =
            "#include \"hooks.hpp\"\n\n"
            "namespace patch {\n\n"
            "using namespace arecomp;\n\n"
            "void install(Runtime& runtime) {\n"
            "    (void)runtime;\n";
        for (const HookSpec& hook : manifest.hooks) {
            source += "\n    // Declared in the manifest at $" + [&] {
                char buf[16];
                std::snprintf(buf, sizeof buf, "%08x", hook.address);
                return std::string(buf);
            }() + ".\n";
            source += "    // runtime.hooks().add(" + hex(hook.address) + ", HookMode::" +
                      (hook.mode == "before"    ? "Before"
                       : hook.mode == "after"   ? "After"
                                                : "Replace") +
                      ", \"" + hook.name + "\",\n" +
                      "    //     [](M68kState& cpu, Runtime& rt) -> uint32_t {\n" +
                      "    //         return cpu.pc;\n" +
                      "    //     });\n";
        }
        source += "}\n\n} // namespace patch\n";
        write_if_absent(root / "patch" / "hooks.cpp", source);
    }

    // --- main.cpp (written once) ------------------------------------------
    {
        std::string main_source =
            "// Entry point for this port. Written once by arecomp; edit freely.\n\n"
            "#include <cstdio>\n"
            "#include <string>\n\n"
            "#include \"amiga_recomp/runtime.hpp\"\n"
            "#include \"blocks.hpp\"\n"
            "#include \"port.hpp\"\n\n"
            "#if ARECOMP_ENABLE_INTERPRETER\n"
            "#include \"amiga_recomp/interpreter.hpp\"\n"
            "#endif\n\n"
            "int main(int argc, char** argv) {\n"
            "    using namespace arecomp;\n\n"
            "    const std::string image = argc > 1 ? argv[1] : port::kDefaultImage;\n\n"
            "    M68kState cpu;\n"
            "    GuestMemory memory(0x00ffffff);\n"
            "    port::configure_memory(memory);\n"
            "    port::configure_harness(memory, cpu);\n"
            "    if (!port::load_image(memory, image)) {\n"
            "        std::fprintf(stderr,\n"
            "                     \"%s: cannot load game image '%s'.\\n\"\n"
            "                     \"This port ships no game data; supply your own.\\n\",\n"
            "                     port::kName, image.c_str());\n"
            "        return 1;\n"
            "    }\n\n"
            "    RuntimeConfig config;\n"
            "#if ARECOMP_ENABLE_INTERPRETER\n"
            "    config.unknown_target = UnknownTargetPolicy::Interpret;\n"
            "#else\n"
            "    config.unknown_target = UnknownTargetPolicy::Fatal;\n"
            "#endif\n\n"
            "    Runtime runtime(memory, config);\n"
            "#if ARECOMP_ENABLE_INTERPRETER\n"
            "    runtime.set_interpreter(&interpret_block);\n"
            "#endif\n"
            "    generated::install_blocks(runtime.blocks());\n"
            "    port::install_hooks(runtime);\n\n"
            "    port::configure_cpu(cpu);\n\n"
            "    runtime.run(cpu);\n\n"
            "    std::printf(\"%s: halted at $%08x after %llu cycles\\n\", port::kName,\n"
            "                cpu.pc, (unsigned long long)cpu.cycles);\n"
            "    std::printf(\"  blocks executed      : %llu\\n\",\n"
            "                (unsigned long long)runtime.stats().blocks_executed);\n"
            "    std::printf(\"  interpreter fallbacks: %llu\\n\",\n"
            "                (unsigned long long)runtime.stats().interpreter_fallbacks);\n"
            "    return 0;\n"
            "}\n";
        write_if_absent(root / "main.cpp", main_source);
    }

    // --- .gitignore, so a port cannot be committed by accident ------------
    write_if_absent(root / ".gitignore",
                    "# A generated port contains translated game code.\n"
                    "# Nothing here belongs in the amiga-recomp repository.\n"
                    "*\n");

    (void)analysis;
    return true;
}

bool write_build_report(const Manifest& manifest, const AnalysisResult& analysis,
                        const CodegenStats& stats, const std::string& path,
                        std::string& error) {
    std::ofstream out(path);
    if (!out) {
        error = "cannot write " + path;
        return false;
    }

    out << "arecomp build report\n"
        << "====================\n\n"
        << "game          : " << manifest.name << "\n"
        << "id            : " << manifest.id << "\n"
        << "machine       : " << manifest.machine << "\n"
        << "entry         : " << hex(manifest.cpu.entry) << "\n\n"
        << "blocks        : " << stats.blocks << "\n"
        << "instructions  : " << stats.instructions << "\n"
        << "code bytes    : " << analysis.byte_coverage() << "\n"
        << "source files  : " << stats.files << "\n\n";

    out << "unresolved indirect transfer sites: "
        << analysis.unresolved_indirect_sites.size() << "\n";
    if (!analysis.unresolved_indirect_sites.empty()) {
        out << "\nThese are computed JMP/JSR targets that static analysis cannot\n"
               "resolve. Run the port with the interpreter fallback enabled,\n"
               "collect the targets it reports, add them to the manifest as\n"
               "[[indirect_target]] entries, and regenerate. The port is finished\n"
               "when this list is empty and the fallback count is zero.\n\n";
        for (u32 site : analysis.unresolved_indirect_sites)
            out << "  " << hex(site) << "\n";
    }

    if (!stats.unsupported.empty()) {
        out << "\nUNTRANSLATED INSTRUCTIONS (this is a build failure):\n";
        for (const std::string& name : stats.unsupported) out << "  " << name << "\n";
    }

    if (!analysis.diagnostics.empty()) {
        out << "\ndiagnostics\n-----------\n";
        for (const Diagnostic& d : analysis.diagnostics) {
            out << (d.severity == Severity::Error     ? "error  "
                    : d.severity == Severity::Warning ? "warning"
                                                      : "note   ")
                << "  " << hex(d.address) << "  " << d.message << "\n";
        }
    }
    return true;
}

} // namespace arecomp
